/**
 * Zod validation schemas for all BIST and general API request params.
 *
 * Usage in routes:
 *   import { lotParamSchema, paginationSchema } from '../utils/schemas';
 *
 *   router.get('/runs', async (req, res, next) => {
 *     const { lotId } = lotParamSchema.parse(req.params);
 *     const { page, limit } = paginationSchema.parse(req.query);
 *     ...
 *   });
 */

import { z } from 'zod';

// ─── Shared primitives ───────────────────────────────────────────────────────

/** cuid() generated by Prisma — starts with 'c', length 25 */
const cuid = z.string().min(1, 'ID is required');

/** String that must be a positive safe integer when coerced */
/** 0-100 percentage */
const percentage = z.coerce.number().min(0).max(100);

// ─── Path params ─────────────────────────────────────────────────────────────

/** { lotId } path param — used on every /lots/:lotId/* route */
export const lotParamSchema = z.object({
  lotId: cuid,
});

/** { lotId, runId } for accessing a specific run record */
export const lotRunParamSchema = lotParamSchema.extend({
  runId: cuid,
});

/** { lotId, chainId } for chain-specific routes */
export const lotChainParamSchema = lotParamSchema.extend({
  chainId: cuid,
});

// ─── Pagination ───────────────────────────────────────────────────────────────

/** Common ?page=&limit= query params with sensible defaults */
export const paginationSchema = z.object({
  page:  z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().min(1).max(1000).default(50),
});

export type PaginationParams = z.infer<typeof paginationSchema>;

// ─── Sorting ─────────────────────────────────────────────────────────────────

export const sortDirSchema = z.enum(['asc', 'desc']).default('asc');

// ─── Scan Chain Run filters ───────────────────────────────────────────────────

export const scanChainRunFilterSchema = paginationSchema.extend({
  /** Filter to a specific chain by its DB id */
  chainId: cuid.optional(),
  /** Only return runs where brokenDetected matches this value */
  broken: z
    .enum(['true', 'false'])
    .transform(v => v === 'true')
    .optional(),
  /** Minimum faults caught */
  minFaults: z.coerce.number().int().min(0).optional(),
  /** Sort field */
  sortBy: z
    .enum(['runIndex', 'totalTimeMs', 'faultsCaught', 'compressionRatio', 'passCount'])
    .default('runIndex'),
  sortDir: sortDirSchema,
});

export type ScanChainRunFilter = z.infer<typeof scanChainRunFilterSchema>;

// ─── MBIST Run filters ────────────────────────────────────────────────────────

/** Valid memory types as stored in the DB */
export const MemoryTypeEnum = z.enum(['SRAM', 'ROM', 'CAM', 'FIFO', 'RF']);

/** Valid algorithm names */
export const AlgorithmEnum = z.enum(['MARCH-C', 'MARCH-LR', 'MARCH-SS', 'MATS+', 'GALOIS']);

export const mbistRunFilterSchema = paginationSchema.extend({
  memoryType:   MemoryTypeEnum.optional(),
  algorithm:    AlgorithmEnum.optional(),
  /** Only return instances with coverage below this threshold */
  maxCoverage:  percentage.optional(),
  /** Only return instances with coverage above this threshold */
  minCoverage:  percentage.optional(),
  /** Return only passing (true) or failing (false) instances */
  passed: z
    .enum(['true', 'false'])
    .transform(v => v === 'true')
    .optional(),
  sortBy: z
    .enum(['instanceName', 'testTimeMs', 'coveragePercent', 'faultsCaught', 'repairAttempts'])
    .default('instanceName'),
  sortDir: sortDirSchema,
});

export type MBISTRunFilter = z.infer<typeof mbistRunFilterSchema>;

// ─── LBIST Run filters ────────────────────────────────────────────────────────

export const lbistRunFilterSchema = paginationSchema.extend({
  /** Filter by signature match status */
  signatureMatch: z
    .enum(['true', 'false'])
    .transform(v => v === 'true')
    .optional(),
  /** Minimum toggle coverage % */
  minToggle: percentage.optional(),
  sortBy: z
    .enum(['instanceName', 'testTimeMs', 'coveragePercent', 'toggleCoverage', 'faultsCaught'])
    .default('instanceName'),
  sortDir: sortDirSchema,
});

export type LBISTRunFilter = z.infer<typeof lbistRunFilterSchema>;

// ─── Domain filter (shared) ───────────────────────────────────────────────────

/** Power-domain filter — matches the normalised values used in the importService */
export const DomainEnum = z.enum([
  'CPU core',
  'GPU block',
  'Memory ctrl',
  'I/O ring',
  'CLKGEN',
  'Analog IP',
  'Digital SoC',
]);

export const domainFilterSchema = z.object({
  domain: DomainEnum.optional(),
});

// ─── Pattern filters ──────────────────────────────────────────────────────────

export const PatternTypeEnum    = z.enum(['SCAN', 'ATPG', 'BIST', 'FUNCTIONAL', 'IDDQ', 'BOUNDARY']);
export const PatternActionEnum  = z.enum(['KEEP', 'REMOVE', 'DEFER', 'MERGE']);
export const DetectPowerEnum    = z.enum(['HIGH', 'MEDIUM', 'LOW']);

export const patternFilterSchema = paginationSchema.extend({
  type:      PatternTypeEnum.optional(),
  action:    PatternActionEnum.optional(),
  domain:    DomainEnum.optional(),
  search:    z.string().trim().max(100).optional(),
  minCoverage: percentage.optional(),
  maxFailRate: percentage.optional(),
  sortBy: z
    .enum(['sequenceIndex', 'testTimeMs', 'faultCoverage', 'failRate', 'patternId'])
    .default('sequenceIndex'),
  sortDir: sortDirSchema,
});

export type PatternFilter = z.infer<typeof patternFilterSchema>;

// ─── Upload validation ────────────────────────────────────────────────────────

/** Body schema for POST /lots/:lotId/upload — validated before parsing begins */
export const uploadBodySchema = z.object({
  product: z.string().trim().min(1).max(64).optional(),
  fab:     z.string().trim().min(1).max(32).optional(),
  tester:  z.string().trim().min(1).max(32).optional(),
});

// ─── Validation middleware helper ─────────────────────────────────────────────

import type { Request, Response, NextFunction } from 'express';
import type { ZodSchema } from 'zod';

/**
 * Express middleware factory.
 * Validates req[target] against the given Zod schema.
 * On failure returns 400 with structured error messages.
 *
 * @example
 *   router.get('/runs', validate('params', lotParamSchema), handler);
 */
export const validate =
  (target: 'params' | 'query' | 'body', schema: ZodSchema) =>
  (req: Request, res: Response, next: NextFunction) => {
    const result = schema.safeParse(req[target]);
    if (!result.success) {
      return res.status(400).json({
        success: false,
        message: 'Validation error',
        errors: result.error.errors.map(e => ({
          field: e.path.join('.'),
          message: e.message,
        })),
      });
    }
    // Replace raw req[target] with the coerced, defaulted, validated object
    (req as any)[target] = result.data;
    next();
  };
